language: node_js
node_js:
  - "5.1"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm install --global typescript typings tslint gulp
  - npm run deploy-dev

script:  gulp build tsdoc
